In [1]:
import numpy as np
#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
array1 = np.array(range(30))
#2.呈上題的array，找出被6除餘1的數的索引

In [10]:
a = array1.reshape(5,6,order = "F")
print(a) #1

[[ 0  5 10 15 20 25]
 [ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]]


In [13]:
for i in range(len(a)) :
    for u in range(len(a[i])) :
        if a[i][u] % 6 == 1 :
            print(i, u)
        

0 5
1 0
2 1
3 2
4 3
